services:
  nullex-postgres:
    image: postgres:16
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: nullex-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
